"""one default provider per kind

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-22

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models  # noqa: F401  -- custom column types are rendered fully qualified

revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Written by hand rather than autogenerated: the partial predicate is what
    # makes it a rule about defaults instead of a rule about kinds.
    op.create_index(
        'uq_providers_default_per_kind',
        'providers',
        ['kind'],
        unique=True,
        sqlite_where=sa.text('is_default'),
    )


def downgrade() -> None:
    op.drop_index('uq_providers_default_per_kind', table_name='providers')
